# Generated by Django 6.0.4 on 2026-04-30 23:01

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_inscription_statut_paiement_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=120)),
                ('periodicite', models.CharField(choices=[('MENSUEL', 'Mensuel'), ('ANNUEL', 'Annuel')], default='MENSUEL', max_length=10)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField(blank=True)),
                ('avantages', models.TextField(blank=True, help_text='Un avantage par ligne')),
                ('actif', models.BooleanField(default=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordre', 'prix', 'libelle'],
            },
        ),
        migrations.AlterModelManagers(
            name='utilisateur',
            managers=[
                ('objects', core.models.UtilisateurManager()),
            ],
        ),
    ]
