# Generated by Django 6.0.4 on 2026-04-30 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_abonnement_alter_utilisateur_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='abonnement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='core.abonnement'),
        ),
    ]
