# Generated by Django 6.0.4 on 2026-05-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_paiement_abonnement'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='typeAcces',
            field=models.CharField(choices=[('INTERNE', 'Interne'), ('EXTERNE', 'Externe')], default='INTERNE', max_length=10),
        ),
    ]
